@echo off
REM Display menu options
echo Welcome to the FedSystems Payments system control!
echo Please select an option:
echo 1. Full setup guide
echo 2. Generate SFTP keys
echo 3. Start all services
echo 4. Stop all services
echo 5. Stop all services and clean up Docker containers and volumes

REM Get user input
set /p option=Enter your choice (1-5):
REM Execute the selected option using simple GOTO labels (safer than nested IF parentheses)
if "%option%"=="1" goto opt1
if "%option%"=="2" goto opt2
if "%option%"=="3" goto opt3
if "%option%"=="4" goto opt4
if "%option%"=="5" goto opt5

echo Invalid option. Please run the script again and select a valid option (1-5).
pause
goto end

:opt1
echo You selected the full setup guide. Please follow the instructions below:
echo 1. Ensure you have Docker and Python installed on your system.
echo 2. Ensure ssh-keygen is available in your PATH for key generation.
echo 3. Check .env file, and change bank names to your desired bank names (all lowercase and with '-' instead of spaces).
echo 3a. You can add or remove banks by following the pattern in the .env file and updating docker-compose.yml accordingly.
echo Continue to generate SFTP keys...
pause
python generate_keys.py
echo SFTP keys generated. You can find them in the SFTP_Keys directory. .pub files are public keys and will be automatically mounted to the sftp container.
echo Private keys (without .pub extension) should be added to your SFTP client for authentication when connecting to the SFTP server.
echo Open docker desktop and make sure docker is running, then continue to starting Docker containers...
pause
echo Starting Docker containers...
docker-compose up -d
echo Docker containers started. You can check their status with 'docker-compose ps'.
echo You can check sftp connection through filezilla or any SFTP client using the following connection details:
echo Host: localhost
echo Port: 2221
echo Username: (one of the bank names you set in the .env file, e.g. baguette-bank)
echo Authentication: Use the corresponding private key from the SFTP_Keys directory that was generated by this script. Folder name is same as username.
echo Alternatively, you can connect through command line using: sftp -oStrictHostKeyChecking=no -i id_rsa -P 2221 baguette-bank@localhost
pause
goto end

:opt2
echo You selected to generate SFTP keys. Running generate_keys.py...
python generate_keys.py
pause
goto end

:opt3
echo You selected to start all services. Starting Docker containers...
docker-compose up -d
pause
goto end

:opt4
echo You selected to stop all services. Stopping Docker containers...
docker-compose down
pause
goto end

:opt5
echo You selected to stop all services and clean up Docker containers and volumes. Stopping and removing Docker containers and volumes...
docker-compose down -v
pause
goto end

:end