# Example of an ach file:
# 101 090000515 0401040182604050900A094101FRB Tungsten           Baguette Bank                  
# 5220Baguette store                      1313131310PPDLEEK PAY        260406   1040104010000001
# 62201010101239               0000015075               Leek store              1040104010000001
# 705A 31 tons of leek purchase!                                                     00010000001
# 62231031031239               0000015075               Leek store              0040104010000002
# 822000000300320411320000000000000000000301501313131310                         040104010000001
# 9000001000001000000030032041132000000000000000000030150                                       
# 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
# 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
# 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

import json
import os
from datetime import datetime

class ACHEntry:
    def __init__(self):
        self.record_type_code = None
        self.transaction_code = None
        self.receiving_dfi_identification = None
        self.check_digit = None
        self.dfi_account_number = None
        self.amount_cents = None
        self.individual_id_number = None
        self.individual_name = None
        self.discretionary_data = None 
        self.addenda_record_indicator = None 
        self.trace_number = None
        self.addenda = []

    def add_addenda(self, addenda):
        self.addenda.append(addenda)

    def parse_record(self, line):
        self.record_type_code = line[0]
        self.transaction_code = line[1:3]
        self.receiving_dfi_identification = line[3:11].strip()
        self.check_digit = line[11]
        self.dfi_account_number = line[12:29].strip()
        self.amount_cents = int(line[29:39]) # Amount in cents, convert to dollars by dividing by 100
        self.individual_id_number = line[39:54].strip()
        self.individual_name = line[54:76].strip()
        self.discretionary_data = line[76:78].strip() # Note: This field is optional and can be used by the originator or ODFI for any purpose they choose. It may contain information that is relevant to the processing of the entry, but it is not standardized and may not be used by all originators or ODFIs.
        self.addenda_record_indicator = line[78] # Note: This field indicates whether there are addenda records associated with this entry. If it is '1', there is at least one addenda record; if it is '0', there are no addenda records.
        self.trace_number = line[79:94].strip() # Note: This field is critical for tracking the transaction through the ACH network and should be unique for each entry. It is often generated by the ODFI and may include a combination of the ODFI's routing number and a sequential number to ensure uniqueness.
        self.addenda = [] # This will hold any addenda records associated with this entry
        return self

    def add_record(self, record : dict):
        """
        Adds a record to the entry.
        record = {
            'record_type_code': None,
            'transaction_code': None,
            'receiving_dfi_identification': None,
            'check_digit': None,
            'dfi_account_number': None,
            'amount_cents': None,
            'individual_id_number': None,
            'individual_name': None,
            'discretionary_data': None, 
            'addenda_record_indicator': None, 
            'trace_number': None
        }
        """
        self.record_type_code = record['record_type_code']
        self.transaction_code = record['transaction_code']
        self.receiving_dfi_identification = record['receiving_dfi_identification']
        self.check_digit = record['check_digit']
        self.dfi_account_number = record['dfi_account_number']
        self.amount_cents = record['amount_cents']
        self.individual_id_number = record['individual_id_number']
        self.individual_name = record['individual_name']
        self.discretionary_data = record['discretionary_data']
        self.addenda_record_indicator = record['addenda_record_indicator']
        self.trace_number = record['trace_number']
        return self
    
    def add_record(self, record_type_code, transaction_code, receiving_dfi_identification, check_digit, dfi_account_number, amount_cents, individual_id_number, individual_name, discretionary_data, addenda_record_indicator, trace_number):
        self.record_type_code = record_type_code
        self.transaction_code = transaction_code
        self.receiving_dfi_identification = receiving_dfi_identification
        self.check_digit = check_digit
        self.dfi_account_number = dfi_account_number
        self.amount_cents = amount_cents
        self.individual_id_number = individual_id_number
        self.individual_name = individual_name
        self.discretionary_data = discretionary_data
        self.addenda_record_indicator = addenda_record_indicator
        self.trace_number = trace_number
        return self

class ACHAddenda:
    def __init__(self):
        self.record_type_code = None
        self.addenda_type_code = None
        self.payment_related_information = None
        self.addenda_sequence_number = None
        self.entry_detail_sequence_number = None

    def parse_record(self, line):
        self.record_type_code = line[0]
        self.addenda_type_code = line[1:3]
        self.payment_related_information = line[3:83].strip() # Note: This is a free-form alphanumeric field that can contain any information related to the payment. It is often used to provide additional details about the transaction, such as invoice numbers, customer references, or other relevant information that can help the receiver understand the purpose of the payment.
        self.addenda_sequence_number = line[83:87].strip() # Note: This field indicates the sequence of addenda records associated with an entry. Hovewer the PPD CCD and WEB only allow one addenda record, so this field should be '0001' for those SEC codes. For other SEC codes that allow multiple addenda records, this field should be incremented for each additional addenda record associated with the same entry.
        self.entry_detail_sequence_number = line[87:94].strip() # Note: This field should match the last 7 digits of the trace number in the corresponding entry detail record to ensure proper association between the addenda and its entry.
        return self

    def add_record(self, record : dict):
        """
        Adds a record to the addenda.
        record = {
            'record_type_code': None,
            'addenda_type_code': None,
            'payment_related_information': None,
            'addenda_sequence_number': None,
            'entry_detail_sequence_number': None
        }
        """
        self.record_type_code = record['record_type_code']
        self.addenda_type_code = record['addenda_type_code']
        self.payment_related_information = record['payment_related_information']
        self.addenda_sequence_number = record['addenda_sequence_number']
        self.entry_detail_sequence_number = record['entry_detail_sequence_number']
        return self

    def add_record(self, record_type_code, addenda_type_code, payment_related_information, addenda_sequence_number, entry_detail_sequence_number):
        self.record_type_code = record_type_code
        self.addenda_type_code = addenda_type_code
        self.payment_related_information = payment_related_information
        self.addenda_sequence_number = addenda_sequence_number
        self.entry_detail_sequence_number = entry_detail_sequence_number
        return self

class ACHBatch:
    def __init__(self):
        self.header = {
            'record_type_code': None,
            'service_class_code': None,
            'company_name': None,
            'company_discretionary_data': None,
            'company_identification': None,
            'standard_entry_class_code': None,
            'company_entry_description': None,
            'company_descriptive_date': None,
            'effective_entry_date': None,
            'settlement_date': None,
            'originator_status_code': None,
            'originating_dfi_identification': None,
            'batch_number': None
        }
        self.entries = []
        self.control = {
            'record_type_code': None,
            'service_class_code': None,
            'entry_count': None,
            'entry_hash': None,
            'total_debit_amount_cents': None,
            'total_credit_amount_cents': None,
            'company_identification': None,
            'message_authentication_code': None,
            'reserved': None,
            'originating_dfi_identification': None,
            'batch_number': None
        }

    def parse_header(self, header_line):
        self.header = {
            'record_type_code': header_line[0],
            'service_class_code': header_line[1:4], # Note: This field identifies the general classification of dollar entries to be exchanged.
            'company_name': header_line[4:20].strip(), # Note: This field is critical for identifying the originator and should be consistent across all entries in the batch. It should be a name that is recognizable to the receiver, such as the name of the business or individual initiating the transaction.
            'company_discretionary_data': header_line[20:40].strip(), # Note: This field is optional and can be used by the originator or ODFI for any purpose they choose. It may contain information that is relevant to the processing of the batch, but it is not standardized and may not be used by all originators or ODFIs. If present, it should be consistent across all entries in the batch.
            'company_identification': header_line[40:50].strip(), # Note: This field is critical for identifying the originator and is often used in conjunction with the ODFI's routing number to uniquely identify the source of the transaction. It must be consistent across all entries in the batch and should be assigned by the ODFI to ensure uniqueness and proper tracking of transactions.
            'standard_entry_class_code': header_line[50:53].strip(), # Note: This is a critical field that determines the type of transaction and has specific formatting rules based on the SEC code
            'company_entry_description': header_line[53:63].strip(), # Note: Some SEC codes require specific values for this field, but in general it's a free-form alphanumeric field
            'company_descriptive_date': header_line[63:69].strip(), # Note: This is a free-form alphanumeric field, not a calendar date
            'effective_entry_date': header_line[69:75].strip(), # Note: This is the YYMMDD format, not a calendar date
            'settlement_date': header_line[75:78].strip(), # Note: This is the Julian date format (DDD), not a calendar date
            'originator_status_code': header_line[78:79].strip(), # Note: This field indicates the status of the originator
            'originating_dfi_identification': header_line[79:87].strip(),
            'batch_number': header_line[87:94].strip()
        }
        return self

    def add_header(self, header : dict):
        """
        Adds a header to the batch.
        header = {
            'record_type_code': None,
            'service_class_code': None,
            'company_name': None,
            'company_discretionary_data': None,
            'company_identification': None,
            'standard_entry_class_code': None,
            'company_entry_description': None,
            'company_descriptive_date': None,
            'effective_entry_date': None,
            'settlement_date': None,
            'originator_status_code': None,
            'originating_dfi_identification': None,
            'batch_number': None
        }
        """
        self.header = header

    def add_header(self, record_type_code, service_class_code, company_name, company_discretionary_data, company_identification, standard_entry_class_code, company_entry_description, company_descriptive_date, effective_entry_date, settlement_date, originator_status_code, originating_dfi_identification, batch_number):
        self.header = {
            'record_type_code': record_type_code,
            'service_class_code': service_class_code,
            'company_name': company_name,
            'company_discretionary_data': company_discretionary_data,
            'company_identification': company_identification,
            'standard_entry_class_code': standard_entry_class_code,
            'company_entry_description': company_entry_description,
            'company_descriptive_date': company_descriptive_date,
            'effective_entry_date': effective_entry_date,
            'settlement_date': settlement_date,
            'originator_status_code': originator_status_code,
            'originating_dfi_identification': originating_dfi_identification,
            'batch_number': batch_number
        }
    
    def add_entry(self, entry):
        self.entries.append(entry)

    def add_control(self, control):
        """
        Adds a control to the batch.
        control = {
            'record_type_code': None,
            'service_class_code': None,
            'entry_count': None,
            'entry_hash': None,
            'total_debit_amount_cents': None,
            'total_credit_amount_cents': None,
            'company_identification': None,
            'message_authentication_code': None,
            'reserved': None,
            'originating_dfi_identification': None,
            'batch_number': None
        }
        """
        self.control = control

    def add_control(self, record_type_code, service_class_code, entry_count, entry_hash, total_debit_amount_cents, total_credit_amount_cents, company_identification, message_authentication_code, reserved, originating_dfi_identification, batch_number):
        self.control = {
            'record_type_code': record_type_code,
            'service_class_code': service_class_code,
            'entry_count': entry_count,
            'entry_hash': entry_hash,
            'total_debit_amount_cents': total_debit_amount_cents,
            'total_credit_amount_cents': total_credit_amount_cents,
            'company_identification': company_identification,
            'message_authentication_code': message_authentication_code,
            'reserved': reserved,
            'originating_dfi_identification': originating_dfi_identification,
            'batch_number': batch_number
        }

    def parse_control(self, control_line):
        self.control = {
            'record_type_code': control_line[0],
            'service_class_code': control_line[1:4].strip(),
            'entry_count': control_line[4:10].strip(),
            'entry_hash': control_line[10:20].strip(),
            'total_debit_amount_cents': int(control_line[20:32]), # Amount in cents, convert to dollars by dividing by 100
            'total_credit_amount_cents': int(control_line[32:44]), # Amount in cents, convert to dollars by dividing by 100
            'company_identification': control_line[44:54].strip(),
            'message_authentication_code': control_line[54:73].strip(), # Note: This field is optional and can be used by the ODFI for any purpose they choose. It may contain information that is relevant to the processing of the batch, but it is not standardized and may not be used by all ODFIs.
            'reserved': control_line[73:79].strip(),
            'originating_dfi_identification': control_line[79:87].strip(),
            'batch_number': control_line[87:94].strip()
        }


class ACHFile:
    def __init__(self):
        self.header = {
            'record_type_code': None, # Always "1"
            'priority_code': None, # Always "01"
            'immediate_destination': None,
            'immediate_origin': None,
            'file_creation_date': None,
            'file_creation_time': None,
            'file_id_modifier': None,
            'record_size': None, # Always "094"
            'blocking_factor': None, # Always "10"
            'format_code': None, # Always "1"
            'immediate_destination_name': None,
            'immediate_origin_name': None,
            'reference_code': None
        }
        self.batches = []
        self.control = None
        self.file_name = None # Name of file if parsed from other source
        self.block_count = None # Number of 10-line blocks in the file, calculated during parsing
        self.lines = None # Lines of the file, stored during parsing for validation purposes
    
    @staticmethod
    def validate_rtn_check_digit(rtn):
        """
        Validate RTN (Routing Transit Number) check digit.
        Formula: (3(d1 + d4 + d7) + 7(d2 + d5 + d8) + (d3 + d6 + d9)) mod 10 = 0
        
        Args:
            rtn: 9-digit routing number as string
            
        Returns:
            True if valid, False otherwise
        """
        if not rtn or len(rtn) != 9 or not rtn.isdigit():
            return False
        
        digits = [int(d) for d in rtn]
        # d1=0, d2=1, d3=2, d4=3, d5=4, d6=5, d7=6, d8=7, d9=8
        checksum = (3 * (digits[0] + digits[3] + digits[6]) + 
                    7 * (digits[1] + digits[4] + digits[7]) + 
                    (digits[2] + digits[5] + digits[8]))
        
        return checksum % 10 == 0
    
    def _parse_lines(self, lines):
        """Private: Reparse the file to apply self calculated control values"""
        self.block_count = len(lines) // 10
        try:
            if not lines:
                raise ValueError("ACH file is empty")
            
            # Checks if the file contains a whole number of 10-blocks (i.e. 10, 20, 30, etc. lines) and raises an error if not
            self.is_file_of_10_blocks(lines)
            
            # Parse header
            try: 
                header_line = lines[0].rstrip('\n\r')
                self.check_line_is_94_chars(header_line)
                self.parse_header(header_line)
            except Exception as e:
                raise ValueError(f"Error parsing header: {e}")
            
            # Parse batches
            current_batch = None
            saw_file_control = False
            for line in lines[1:]:
                line = line.rstrip('\n\r')
                self.check_line_is_94_chars(line)
                record_type_code = line[0]

                if saw_file_control:
                    if line != '9' * 94:
                        raise ValueError("Found non-padding content after file control record")
                    continue

                if record_type_code == '5': # Batch header
                    if current_batch is not None:
                        raise ValueError("Found batch header while already processing a batch")
                    current_batch = ACHBatch().parse_header(line)
                elif record_type_code == '6': # Entry detail
                    if current_batch is None:
                        raise ValueError("Found entry detail without a batch header")
                    current_batch.add_entry(ACHEntry().parse_record(line))
                elif record_type_code == '7': # Addenda record
                    if current_batch is None:
                        raise ValueError("Found addenda record without a batch header")
                    if not current_batch.entries:
                        raise ValueError("Found addenda record without an entry detail")
                    current_batch.entries[-1].addenda.append(ACHAddenda().parse_record(line))
                elif record_type_code == '8': # Batch control
                    if current_batch is None:
                        raise ValueError("Found batch control without a batch header")
                    current_batch.parse_control(line)
                    self.add_batch(current_batch)
                    current_batch = None
                elif record_type_code == '9': # File control
                    if current_batch is not None:
                        raise ValueError("Found file control while still processing a batch")
                    if self.control is None:
                        self.parse_control(line)
                        saw_file_control = True
                    elif line != '9' * 94:
                        raise ValueError("Expected all-9 padding after file control record")
                else:
                    raise ValueError(f"Unknown record type code: {record_type_code}")
        except Exception as e:
            raise

    def parse(self, file_path, check_formatting=False):
        """Parses an ACH file from the given file path."""

        def build_header_line():
            file_id_modifier = self.header.get('file_id_modifier') or ''
            return f"FH,1,LIVE"

        def build_format_error_ack(message):
            return "\n".join([
                build_header_line(),
                f"E,F,0,9999,{message}",
            ])

        if not os.path.isabs(file_path):
            script_dir = os.path.dirname(os.path.abspath(__file__))
            file_path = os.path.join(script_dir, file_path)
        
        with open(file_path, 'r') as f:
            lines = f.readlines()
        self.file_name = os.path.basename(file_path)
        self.lines = lines

        self.block_count = len(lines) // 10
        try:
            if not lines:
                raise ValueError("ACH file is empty")
            
            # Checks if the file contains a whole number of 10-blocks (i.e. 10, 20, 30, etc. lines) and raises an error if not
            self.is_file_of_10_blocks(lines)
            
            # Parse header
            try: 
                header_line = lines[0].rstrip('\n\r')
                self.check_line_is_94_chars(header_line)
                self.parse_header(header_line)
            except Exception as e:
                raise ValueError(f"Error parsing header: {e}")
            
            # Parse batches
            current_batch = None
            saw_file_control = False
            for line in lines[1:]:
                line = line.rstrip('\n\r')
                self.check_line_is_94_chars(line)
                record_type_code = line[0]

                if saw_file_control:
                    if line != '9' * 94:
                        raise ValueError("Found non-padding content after file control record")
                    continue

                if record_type_code == '5': # Batch header
                    if current_batch is not None:
                        raise ValueError("Found batch header while already processing a batch")
                    current_batch = ACHBatch().parse_header(line)
                elif record_type_code == '6': # Entry detail
                    if current_batch is None:
                        raise ValueError("Found entry detail without a batch header")
                    current_batch.add_entry(ACHEntry().parse_record(line))
                elif record_type_code == '7': # Addenda record
                    if current_batch is None:
                        raise ValueError("Found addenda record without a batch header")
                    if not current_batch.entries:
                        raise ValueError("Found addenda record without an entry detail")
                    current_batch.entries[-1].addenda.append(ACHAddenda().parse_record(line))
                elif record_type_code == '8': # Batch control
                    if current_batch is None:
                        raise ValueError("Found batch control without a batch header")
                    current_batch.parse_control(line)
                    self.add_batch(current_batch)
                    current_batch = None
                elif record_type_code == '9': # File control
                    if current_batch is not None:
                        raise ValueError("Found file control while still processing a batch")
                    if self.control is None:
                        self.parse_control(line)
                        saw_file_control = True
                    elif line != '9' * 94:
                        raise ValueError("Expected all-9 padding after file control record")
                else:
                    raise ValueError(f"Unknown record type code: {record_type_code}")
        except Exception as e:
            if check_formatting:
                return build_format_error_ack(str(e))
            else:
                raise

    def check_line_is_94_chars(self, line):
        if len(line) != 94:
            raise ValueError(f"Line is not 94 characters long: {line}")
        
    def is_file_of_10_blocks(self, lines):
        if len(lines) % 10 != 0:
            raise ValueError(f"File does not contain a whole number of 10-blocks: {len(lines)} lines")
        
    def parse_header(self, line):
        self.header = {
            'record_type_code': line[0],
            'priority_code': line[1:3],
            'immediate_destination': line[3:13].strip(),
            'immediate_origin': line[13:23].strip(),
            'file_creation_date': line[23:29], # YYMMDD format
            'file_creation_time': line[29:33], # HHMM format
            'file_id_modifier': line[33], # A-Z, 0-9
            'record_size': line[34:37], # Always "094"
            'blocking_factor': line[37:39], # Always "10"
            'format_code': line[39], # Always "1"
            'immediate_destination_name': line[40:63].strip(),
            'immediate_origin_name': line[63:86].strip(),
            'reference_code': line[86:94].strip()
        }

    def parse_control(self, line):
        self.control = {
            'record_type_code': line[0],
            'batch_count': line[1:7].strip(),
            'block_count': line[7:13].strip(),
            'entry_count': line[13:21].strip(),
            'entry_hash': line[21:31].strip(),
            'total_debit_amount_cents': int(line[31:43]), # Amount in cents, convert to dollars by dividing by 100
            'total_credit_amount_cents': int(line[43:55]), # Amount in cents, convert to dollars by dividing by 100
            'reserved': line[55:94].strip()
        }
    
    def add_batch(self, batch):
        self.batches.append(batch)

    def get_header(self):
        return self.header

    def get_batches(self):
        return self.batches

    def get_control(self):
        return self.control
    
    def get_block_number(self):
        return self.block_count

    def build_ach(self, self_calculate_control=True):
        """Builds the ACH file content as a list of lines, where each line is a 94-character string.
        If self_calculate_control is True, the control record will be calculated based on the batches and entries in the file. If False, the control record will be built based on the current value of self.control, which can be manually set when creating the file.
        if True, the content might get overwritten.
        
        example of return value:
        [
            "101 090000515 0401040182604050900A094101FRB Tungsten           Baguette Bank                  ",
            "5220Baguette store                      1313131310PPDLEEK PAY        260406   1040104010000001",
            "62201010101239               0000015075               Leek store              1040104010000001",
            "705A 31 tons of leek purchase!                                                     00010000001",
            "62231031031239               0000015075               Leek store              0040104010000002",
            "822000000300320411320000000000000000000301501313131310                         040104010000001",
            "9000001000001000000030032041132000000000000000000030150                                       ",
        ]
        """
        def fit_left(value, width):
            """Truncate then left-pad to an exact width."""
            text = '' if value is None else str(value)
            return text[:width].ljust(width)

        def fit_right(value, width):
            """Truncate from the left then right-pad to an exact width."""
            text = '' if value is None else str(value)
            return text[-width:].rjust(width)

        def fit_zero_right(value, width):
            """Keep digits/characters right-aligned and zero padded to exact width."""
            text = '' if value is None else str(value)
            return text[-width:].zfill(width)

        def build_header_line():
            """Something like this 94-character line empty space filled with spaces:
            101 090000515 0401040182604050900A094101FRB Tungsten           Baguette Bank                  
            """
            file_id_modifier = fit_left(self.header.get('file_id_modifier') or 'A', 1)
            return (
                "1"
                f"{fit_left(self.header.get('priority_code'), 2)}"
                f"{fit_right(self.header.get('immediate_destination'), 10)}"
                f"{fit_right(self.header.get('immediate_origin'), 10)}"
                f"{fit_left(self.header.get('file_creation_date'), 6)}"
                f"{fit_left(self.header.get('file_creation_time'), 4)}"
                f"{file_id_modifier}"
                f"{fit_left(self.header.get('record_size'), 3)}"
                f"{fit_left(self.header.get('blocking_factor'), 2)}"
                f"{fit_left(self.header.get('format_code'), 1)}"
                f"{fit_left(self.header.get('immediate_destination_name'), 23)}"
                f"{fit_left(self.header.get('immediate_origin_name'), 23)}"
                f"{fit_left(self.header.get('reference_code'), 8)}"
            )
        
        def build_file_control_line():
            """Something like this 94-character line empty space filled with spaces:
            9000001000001000000030032041132000000000000000000030150                                       
            """
            if self_calculate_control:
                batch_count = len(self.batches)
                entry_and_addenda_count = sum(len(batch.entries) + sum(len(entry.addenda) for entry in batch.entries) for batch in self.batches)
                total_lines_before_padding = 2 + (batch_count * 2) + entry_and_addenda_count # file header + file control + batch headers/controls + entry/addenda records
                block_count = (total_lines_before_padding + 9) // 10
                entry_count = sum(1 + len(entry.addenda) for batch in self.batches for entry in batch.entries)
                entry_hash = sum(int(entry.receiving_dfi_identification) for batch in self.batches for entry in batch.entries) % 10**10
                total_debit_amount_cents = sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['27', '37', '26', '36']) # Debit transaction codes (27 and 37 are for prearranged payments and reversals, 26 and 36 are for return entries)
                total_credit_amount_cents = sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['22', '32', '21', '31']) # Credit transaction codes (22 and 32 are for prearranged payments and reversals, 21 and 31 are for return entries)
                reserved = ''
                file_control_line = (
                    f"9{batch_count:06}{block_count:06}{entry_count:08}{entry_hash:010}{total_debit_amount_cents:012}{total_credit_amount_cents:012}{fit_left(reserved, 39)}"
                )
                return file_control_line
            else:
                file_control_line = (
                    f"9{self.control['batch_count']:06}{self.control['block_count']:06}{self.control['entry_count']:08}{self.control['entry_hash']:010}{self.control['total_debit_amount_cents']:012}{self.control['total_credit_amount_cents']:012}{fit_left(self.control.get('reserved'), 39)}"
                )
                return file_control_line
            
        def build_batch(batch):
            def build_batch_header_line():
                """Something like this 94-character line empty space filled with spaces:
                5220Baguette store                      1313131310PPDLEEK PAY        260406   1040104010000001
                """
                return (
                    "5"
                    f"{fit_left(batch.header.get('service_class_code'), 3)}"
                    f"{fit_left(batch.header.get('company_name'), 16)}"
                    f"{fit_left(batch.header.get('company_discretionary_data'), 20)}"
                    f"{fit_left(batch.header.get('company_identification'), 10)}"
                    f"{fit_left(batch.header.get('standard_entry_class_code'), 3)}"
                    f"{fit_left(batch.header.get('company_entry_description'), 10)}"
                    f"{fit_left(batch.header.get('company_descriptive_date'), 6)}"
                    f"{fit_left(batch.header.get('effective_entry_date'), 6)}"
                    f"{fit_left(batch.header.get('settlement_date'), 3)}"
                    f"{fit_left(batch.header.get('originator_status_code'), 1)}"
                    f"{fit_left(batch.header.get('originating_dfi_identification'), 8)}"
                    f"{fit_left(batch.header.get('batch_number'), 7)}"
                )

            def build_entry_line(entry):
                """Something like this 94-character line empty space filled with spaces:
                62201010101239               0000015075               Leek store              1040104010000001
                """
                return (
                    "6"
                    f"{fit_left(entry.transaction_code, 2)}"
                    f"{fit_right(entry.receiving_dfi_identification, 8)}"
                    f"{fit_left(entry.check_digit, 1)}"
                    f"{fit_left(entry.dfi_account_number, 17)}"
                    f"{fit_zero_right(entry.amount_cents, 10)}"
                    f"{fit_left(entry.individual_id_number, 15)}"
                    f"{fit_left(entry.individual_name, 22)}"
                    f"{fit_left(entry.discretionary_data, 2)}"
                    f"{fit_left(entry.addenda_record_indicator, 1)}"
                    f"{fit_left(entry.trace_number, 15)}"
                )
            
            def build_addenda_line(addenda):
                """Something like this 94-character line empty space filled with spaces:
                705A 31 tons of leek purchase!                                                     00010000001
                """
                return (
                    "7"
                    f"{fit_left(addenda.addenda_type_code, 2)}"
                    f"{fit_left(addenda.payment_related_information, 80)}"
                    f"{fit_left(addenda.addenda_sequence_number, 4)}"
                    f"{fit_left(addenda.entry_detail_sequence_number, 7)}"
                )
            
            def build_batch_control_line():
                    """Something like this 94-character line empty space filled with spaces:
                    822000000300320411320000000000000000000301501313131310                         040104010000001
                    """
                
            batch_lines = [build_batch_header_line()]
            for entry in batch.entries:
                batch_lines.append(build_entry_line(entry))
                for addenda in entry.addenda:
                    batch_lines.append(build_addenda_line(addenda))
            if self_calculate_control:
                # Calculate control values based on batch content
                entry_count = sum(1 + len(entry.addenda) for entry in batch.entries)
                entry_hash = sum(int(entry.receiving_dfi_identification) for entry in batch.entries) % 10**10
                total_debit_amount_cents = sum(entry.amount_cents for entry in batch.entries if entry.transaction_code in ['26', '27', '36', '37']) # Debit transaction codes
                total_credit_amount_cents = sum(entry.amount_cents for entry in batch.entries if entry.transaction_code in ['21', '22', '31', '32']) # Credit transaction codes
                batch_control_line = (
                    f"8{batch.header['service_class_code']}"
                    f"{entry_count:06}"
                    f"{entry_hash:010}"
                    f"{total_debit_amount_cents:012}"
                    f"{total_credit_amount_cents:012}"
                    f"{fit_left(batch.header.get('company_identification'), 10)}"
                    f"{fit_left('', 19)}"
                    f"{fit_left('', 6)}"
                    f"{fit_zero_right(batch.header.get('originating_dfi_identification'), 8)}"
                    f"{fit_zero_right(batch.header.get('batch_number'), 7)}"
                )
            else:
                batch_control_line = (
                    f"8{batch.control['service_class_code']}"
                    f"{batch.control['entry_count']:06}"
                    f"{int(batch.control['entry_hash']) % 10**10:010}"
                    f"{int(batch.control['total_debit_amount_cents']):012}"
                    f"{int(batch.control['total_credit_amount_cents']):012}"
                    f"{fit_left(batch.control.get('company_identification'), 10)}"
                    f"{fit_left(batch.control.get('message_authentication_code'), 19)}"
                    f"{fit_left(batch.control.get('reserved'), 6)}"
                    f"{fit_zero_right(batch.control.get('originating_dfi_identification'), 8)}"
                    f"{fit_zero_right(batch.control.get('batch_number'), 7)}"
                )
            batch_lines.append(batch_control_line)
            return batch_lines
        
        ach_file_lines = [build_header_line()]

        for batch in self.batches:
            ach_file_lines.extend(build_batch(batch))  

        ach_file_lines.append(build_file_control_line())

        #Check if the file contains a whole number of 10-blocks (i.e. 10, 20, 30, etc. lines) and raises an error if not
        no_of_lines = len(ach_file_lines)

        if no_of_lines % 10 != 0:
            # If not, we add padding lines of 9s until it does
            padding_lines_needed = (10 - (no_of_lines % 10)) % 10
            ach_file_lines.extend(['9' * 94] * padding_lines_needed)

        # Enforce exact fixed-width lines for all built records.
        for line in ach_file_lines:
            if len(line) != 94:
                raise ValueError(f"Built ACH line is not 94 characters: {line}")

        if self_calculate_control:
            # Clear current values
            self.header = {
                'record_type_code': None,
                'priority_code': None,
                'immediate_destination': None,
                'immediate_origin': None,
                'file_creation_date': None,
                'file_creation_time': None,
                'file_id_modifier': None,
                'record_size': None,
                'blocking_factor': None,
                'format_code': None,
                'immediate_destination_name': None,
                'immediate_origin_name': None,
                'reference_code': None
            }
            self.control = None
            self.batches = []

            self._parse_lines(ach_file_lines) # Re-parse to apply self calculated control values and ensure everything is correct

        return ach_file_lines
    
    def validate(self, is_parsed=False, immediate_destination=None, immediate_origin=None):
        """
        Validates the ACH file and returns an ACK string.
        - is_parsed: If true, this will validate if the file is made of 10-line blocks, requires the file to be parsed from .ach file.
        - immediate_destination: If provided, this will validate that the immediate destination in the header matches the expected value.
        - immediate_origin: If provided, this will validate that the immediate origin in the header matches the expected value.
        """
        line_errors= []
        
        def build_header_line():
            file_id_modifier = self.header.get('file_id_modifier') or ''
            return f"FH,1,LIVE,{file_id_modifier}"

        def build_success_ack():
            if is_parsed:
                if not self.file_name:
                    raise ValueError("It looks like you're trying to pass unparsed data to the validate function. To use this function, create the .ach file first and than parse it using the parse function.")
                return "\n".join([
                        build_header_line(),
                        f"R,{self.get_block_number()},{self.get_block_number()*10}",
                    ])
            else:
                return "\n".join([
                    build_header_line(),
                    "File is valid, to generate successful ACK generate the .ach file, parse it using the parse function and then call validate with is_parsed=True",
                ])

        def build_format_error_ack(message):
            return "\n".join([
                build_header_line(),
                f"E,F,0,9999,{message}",
            ])

        def build_line_error_ack(errors):
            lines = [build_header_line()]
            for error in errors:
                if isinstance(error, dict):
                    error_type = error.get('error_type', 'R')
                    line_number = error.get('line_number', 0)
                    error_code = error.get('error_code', 5000)
                    message = error.get('message', 'Invalid Account')
                else:
                    if len(error) == 2:
                        line_number, message = error
                        error_type = 'L'
                        error_code = 5000
                    elif len(error) == 3:
                        line_number, error_code, message = error
                        error_type = 'L'
                    else:
                        error_type, line_number, error_code, message = error

                lines.append(f"E,{error_type},{line_number},{error_code},{message}")

            return "\n".join(lines)

        def check_immediate_destination():
            if immediate_destination and self.header['immediate_destination'] != immediate_destination:
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1001,
                    'message': f"Immediate destination does not match expected value: {self.header['immediate_destination']} != {immediate_destination}"
                })

            if not self.validate_rtn_check_digit(self.header['immediate_destination']):
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1007,
                    'message': f"Invalid RTN check digit in immediate destination: {self.header['immediate_destination']}"
                })
            
        def check_immediate_origin():
            if immediate_origin and self.header['immediate_origin'] != immediate_origin:
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1002,
                    'message': f"Immediate origin does not match expected value: {self.header['immediate_origin']} != {immediate_origin}"
                })

            if not self.validate_rtn_check_digit(self.header['immediate_origin']):
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1008,
                    'message': f"Invalid RTN check digit in immediate origin: {self.header['immediate_origin']}"
                })

        def check_entry_rtns():
            """Validate RTN check digits for all entry details"""
            line_number = 2  # Start after header
            for batch_idx, batch in enumerate(self.batches):
                for entry_idx, entry in enumerate(batch.entries):
                    rtn = str(entry.receiving_dfi_identification) + str(entry.check_digit)
                    if rtn and not self.validate_rtn_check_digit(rtn):
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5001,
                            'message': f"Invalid RTN check digit: {rtn}"
                        })
                    if entry.addenda_record_indicator == '1' and not entry.addenda:
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5002,
                            'message': f"Addenda record indicator is '1' but no addenda records found for entry with trace number {entry.trace_number}"
                        })
                    
                    if entry.addenda_record_indicator == '0' and entry.addenda:
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5003,
                            'message': f"Addenda record indicator is '0' but addenda records found for entry with trace number {entry.trace_number}"
                        })

                    if entry.addenda_record_indicator == '0':
                        line_number += 1
                    else:
                        line_number += 1 + len(entry.addenda)

        def check_header():
            header = self.header
            control = self.control

            if header['record_type_code'] != '1':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1000,
                    'message': f"Invalid record type code in header: {header['record_type_code']}"
                })
            
            if header['priority_code'] != '01':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1003,
                    'message': f"Invalid priority code in header: {header['priority_code']}"
                })
            
            if header['record_size'] != '094':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1004,
                    'message': f"Invalid record size in header: {header['record_size']}"
                })

            if header['blocking_factor'] != '10':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1005,
                    'message': f"Invalid blocking factor in header: {header['blocking_factor']}"
                })

            if header['format_code'] != '1':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1006,
                    'message': f"Invalid format code in header: {header['format_code']}"
                })

            line_count = 1 + sum(1 + len(entry.addenda) for batch in self.batches for entry in batch.entries) + len(self.batches)*2 + 1 # header + entry and addenda records + batch headers and controls + file control

            if control['record_type_code'] != '9':
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3000,
                    'message': f"Invalid record type code in file control: {control['record_type_code']}"
                })

            if control['batch_count'] != str(len(self.batches)).zfill(6):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3002,
                    'message': f"Batch count in file control does not match actual number of batches in file: {control['batch_count']} != {str(len(self.batches)).zfill(6)}"
                })
            
            if control['block_count'] != str(self.block_count).zfill(6):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3003,
                    'message': f"Block count in file control does not match actual number of blocks in file: {control['block_count']} != {str(self.block_count).zfill(6)}"
                })

            entry_and_addenda_count = sum(1 + len(entry.addenda) for batch in self.batches for entry in batch.entries)
            if control['entry_count'] != str(entry_and_addenda_count).zfill(8):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3004,
                    'message': f"Entry count in file control does not match actual number of entry and addenda records in file: {control['entry_count']} != {str(entry_and_addenda_count).zfill(8)}"
                })

            entry_hash = sum(int(entry.receiving_dfi_identification) for batch in self.batches for entry in batch.entries) % 10**10
            if control['entry_hash'] != str(entry_hash).zfill(10):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3005,
                    'message': f"Entry hash in file control does not match calculated entry hash: {control['entry_hash']} != {str(entry_hash).zfill(10)}"
                })

            if control['total_debit_amount_cents'] != sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['26', '27', '36', '37', '47', '57', '67', '87']):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3006,
                    'message': f"Total debit amount in file control does not match calculated total debit amount: {control['total_debit_amount_cents']} != {sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['26', '27', '36', '37', '47', '57', '67', '87'])}"
                })

            if control['total_credit_amount_cents'] != sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['21', '22', '31', '32', '42', '52', '62', '82']):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3007,
                    'message': f"Total credit amount in file control does not match calculated total credit amount: {control['total_credit_amount_cents']} != {sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['21', '22', '31', '32', '42', '52', '62', '82'])}"
                })

            if control['reserved'] != '':
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3008,
                    'message': f"Reserved field in file control is not empty: {control['reserved']}"
                })

            if is_parsed and self.batches:
                check_entry_rtns()
        
        def check_batch(start_line_number):
            line_number = start_line_number
            for batch_idx, batch in enumerate(self.batches):
                if batch.header['record_type_code'] != '5':
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2000,
                        'message': f"Invalid record type code in batch header: {batch.header['record_type_code']}"
                    })
                if batch.header['service_class_code'] not in ['200', '220', '225']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2001,
                        'message': f"Invalid service class code in batch header: {batch.header['service_class_code']} 200 - Mixed Debits and Credits, 220 - Credits Only, 225 - Debits Only"
                    })

                if batch.header['standard_entry_class_code'] not in ['PPD', 'CCD']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2002,
                        'message': f"Invalid standard entry class code in batch header: {batch.header['standard_entry_class_code']} Only 2 standard entry class codes are currently supported: PPD - Prearranged Payment and Deposit Entry, CCD - Corporate Credit or Debit"
                    })

                if batch.header['originator_status_code'] not in ['1', '2', '3']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2003,
                        'message': f"Invalid originator status code in batch header: {batch.header['originator_status_code']} 1 - Originator is a financial institution, 2 - Originator is a non-financial institution, 3 - Originator is a government entity"
                    })

                if batch.header['originating_dfi_identification'] != self.header['immediate_origin'][:8]:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2004,
                        'message': f"Originating DFI identification in batch header does not match immediate origin in file header: {batch.header['originating_dfi_identification']} != {self.header['immediate_origin'][:8]}"
                    })

                previous_entry_trace_number = int(batch.header['originating_dfi_identification'] + '0000000')
                for entry in batch.entries:
                    if batch.header['service_class_code'] == '225':
                        if entry.transaction_code not in ['26', '27', '28', '36', '37', '38', '47', '48', '57', '58', '67', '68', '87', '88']:
                            line_errors.append({
                                'error_type': 'E',
                                'line_number': line_number,
                                'error_code': 3001,
                                'message': f"Invalid transaction code for debit entry in batch with service class code 225: {entry.transaction_code}"
                            })

                    if batch.header['service_class_code'] == '220':
                        if entry.transaction_code not in ['21','22', '23', '31', '32', '33', '42', '43', '52', '53', '62', '63', '82', '83']:
                            line_errors.append({
                                'error_type': 'E',
                                'line_number': line_number,
                                'error_code': 3000,
                                'message': f"Invalid transaction code for credit entry in batch with service class code 220: {entry.transaction_code}"
                            })

                    if int(entry.trace_number) <= previous_entry_trace_number:
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5004,
                            'message': f"Entry trace number out of order: {entry.trace_number} should be greater than {previous_entry_trace_number} (trace numbers can skip but not go backwards)"
                        })
                    previous_entry_trace_number = int(entry.trace_number)
                    
                    line_number += 1 + len(entry.addenda)  # Account for entry detail and addenda lines

                line_number += 1  # Place self at batch control line

                entry_and_addenda_count = sum(1 + len(entry.addenda) for entry in batch.entries)
                if batch.control['entry_count'] != str(entry_and_addenda_count).zfill(6):
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2005,
                        'message': f"Entry count in batch control does not match actual number of entry and addenda records in batch: {batch.control['entry_count']} != {str(entry_and_addenda_count).zfill(6)}"
                    })
                
                entry_hash = sum(int(entry.receiving_dfi_identification) for entry in batch.entries) % 10**10
                if batch.control['entry_hash'] != str(entry_hash).zfill(10):
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2006,
                        'message': f"Entry hash in batch control does not match calculated entry hash: {batch.control['entry_hash']} != {str(entry_hash).zfill(10)}"
                    })

                total_debit_amount_cents = sum(entry.amount_cents for entry in batch.entries if entry.transaction_code in ['26', '27', '36', '37', '47', '57', '67', '87'])
                if batch.control['total_debit_amount_cents'] != total_debit_amount_cents:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2007,
                        'message': f"Total debit amount in batch control does not match calculated total debit amount: {batch.control['total_debit_amount_cents']} != {total_debit_amount_cents}"
                    })

                total_credit_amount_cents = sum(entry.amount_cents for entry in batch.entries if entry.transaction_code in ['21', '22', '31', '32', '42', '52', '62', '82'])
                if batch.control['total_credit_amount_cents'] != total_credit_amount_cents:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2008,
                        'message': f"Total credit amount in batch control does not match calculated total credit amount: {batch.control['total_credit_amount_cents']} != {total_credit_amount_cents}"
                    })

                if batch.control['company_identification'] != batch.header['company_identification']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2009,
                        'message': f"Company identification in batch control does not match company identification in batch header: {batch.control['company_identification']} != {batch.header['company_identification']}"
                    })

                return line_number + 1  # Return line number of next batch header or file control after this batch

        try:
            check_immediate_destination()
            check_immediate_origin()
            check_header()
            last_number = 2
            for batch in self.batches:
                last_number = check_batch(last_number)
        except ValueError as error:
            return build_format_error_ack(str(error))

        if line_errors:
            return build_line_error_ack(line_errors)

        return build_success_ack()
    
def jsonToAchFile(json_data, settlement_date=None):
    """Function to create an ACHFile object from a JSON representation of the file content.

    Controls will be calculated based on the content of the batches and entries, so they don't need to be provided in the JSON.

    The JSON structure should be as follows:
{
    "header": {
        "immediate_destination": "090000515",
        "immediate_origin": "040104018",
        "file_creation_date": "240610", # Can be none, in which case it will be set to the current date in YYMMDD format
        "file_creation_time": "1200", # Can be none, in which case it will be set to the current time
        "file_id_modifier": "A",
        "immediate_destination_name": "FRB Tungsten",
        "immediate_origin_name": "Baguette store"
    },
    "batches": [
        {
            "header": {
                "service_class_code": "200", # 200 for mixed debits and credits, 220 for credits only, 225 for debits only, can be left null to figure out automagically
                "company_name": "Baguette store",
                "company_discretionary_data": "",
                "company_identification": "1313131310",
                "standard_entry_class_code": "PPD", # Currently only PPD and CCD are supported
                "company_entry_description": "LEEK PAY", # Will be truncated to 10 characters if longer
                "company_descriptive_date": "240610", # Can be none, in which case it will be set to the header date in YYMMDD format
                "effective_entry_date": "240610", # Can be none, in which case it will be set to the header date in YYMMDD format
                "settlement_date": "", # Will be set by the ACH operator, should be left empty
                "originator_status_code": "1",
                "originating_dfi_identification": "04010401"
            },
            "entries": [
                {
                    "transaction_code": "22",
                    "receiving_dfi_rtn": "010101012",
                    "dfi_account_number": "123456789",
                    "amount_cents": 100,
                    "individual_id_number": "",
                    "individual_name": "Leek store",
                    "trace_number": "040104010000001", # Can be null if needs to be generated, HOWEVER, if previously provided it should be the same! i.e. If you want to return entry, or you're forwarding the file.
                    "addenda": [
                        {
                            "payment_related_information": "31 tons of leek purchase!", # Will be truncated to 80 characters if longer
                        }
                    ]
                },
                {
                    "transaction_code": "22",
                    "receiving_dfi_rtn": "010101012",
                    "dfi_account_number": "123456789",
                    "amount_cents": 100,
                    "individual_id_number": "",
                    "individual_name": "Leek store",
                    "trace_number": "040104010000001",
                    "addenda": [
                        {
                            "payment_related_information": "31 tons of leek purchase!", # Will be truncated to 80 characters if longer
                        }
                    ]
                }
            ],
        }
    ],
}
    """
    ach_file = ACHFile()
    ach_file.header = {
        'record_type_code': '1',
        'priority_code': '01',
        'immediate_destination': json_data['header'].get('immediate_destination') or '',
        'immediate_origin': json_data['header'].get('immediate_origin') or '',
        'file_creation_date': json_data['header'].get('file_creation_date') or datetime.now().strftime('%y%m%d'),
        'file_creation_time': json_data['header'].get('file_creation_time') or datetime.now().strftime('%H%M'),
        'file_id_modifier': json_data['header'].get('file_id_modifier') or 'A',
        'record_size': '094',
        'blocking_factor': '10',
        'format_code': '1',
        'immediate_destination_name': json_data['header'].get('immediate_destination_name') or '',
        'immediate_origin_name': json_data['header'].get('immediate_origin_name') or '',
        'reference_code': json_data['header'].get('reference_code') or ''
    }

    for batch_index, batch_data in enumerate(json_data['batches'], start=1):
        batch = ACHBatch()

        batch_sevice_class_code = batch_data['header'].get('service_class_code') or (
            '225' if all(entry['transaction_code'] in ['26', '27', '36', '37', '47', '57', '67', '87'] for entry in batch_data['entries']) else
            '220' if all(entry['transaction_code'] in ['21', '22', '31', '32', '42', '52', '62', '82'] for entry in batch_data['entries']) else
            '200'
        )

        batch.header = {
            'record_type_code': '5',
            'service_class_code': batch_sevice_class_code,
            'company_name': batch_data['header'].get('company_name') or '',
            'company_discretionary_data': batch_data['header'].get('company_discretionary_data') or '',
            'company_identification': batch_data['header'].get('company_identification') or '',
            'standard_entry_class_code': batch_data['header'].get('standard_entry_class_code') or '',
            'company_entry_description': batch_data['header'].get('company_entry_description') or '', # Truncate to 10 characters if longer
            'company_descriptive_date': batch_data['header'].get('company_descriptive_date') or ach_file.header['file_creation_date'],
            'effective_entry_date': batch_data['header'].get('effective_entry_date') or ach_file.header['file_creation_date'],
            'settlement_date': settlement_date or '', # Will be set by the ACH operator, should be left empty
            'originator_status_code': batch_data['header'].get('originator_status_code') or '1',
            'originating_dfi_identification': batch_data['header'].get('originating_dfi_identification') or '',
            'batch_number': batch_data['header'].get('batch_number') or f'{batch_index:07d}'
        }

        for entry_index, entry_data in enumerate(batch_data['entries'], start=1):
            entry = ACHEntry().add_record(
                record_type_code='6',
                transaction_code=entry_data.get('transaction_code') or '',
                receiving_dfi_identification=entry_data.get('receiving_dfi_rtn', '')[:-1],
                check_digit=entry_data.get('receiving_dfi_rtn', '')[-1],
                dfi_account_number=entry_data.get('dfi_account_number') or '',
                amount_cents=entry_data.get('amount_cents') or 0,
                individual_id_number=entry_data.get('individual_id_number') or '',
                individual_name=entry_data.get('individual_name') or '',
                discretionary_data=entry_data.get('discretionary_data') or '',
                addenda_record_indicator='1' if entry_data.get('addenda') else '0',
                trace_number=entry_data.get('trace_number') or f'{batch_data["header"]["originating_dfi_identification"]}{entry_index:07d}' # Originating DFI identification (8 digits) + batch number (7 digits)
            )

            for addenda_index, addenda_data in enumerate(entry_data.get('addenda', []), start=1):
                addenda = ACHAddenda().add_record(
                    record_type_code='7',
                    addenda_type_code=addenda_data.get('addenda_type_code', '05'),
                    payment_related_information=addenda_data.get('payment_related_information', '')[:80], # Truncate to 80 characters if longer
                    addenda_sequence_number=f'{addenda_index:04d}', # Generates next addenda sequence number based on, will reset for each entry
                    entry_detail_sequence_number=entry.trace_number[-7:] # The entry detail sequence number should match the last 7 digits of the trace number
                )
                entry.add_addenda(addenda)
            batch.add_entry(entry)
        ach_file.add_batch(batch)
    ach_file.build_ach() # Build the ACH file to calculate control values based on the content
    return ach_file

def achFileToJson(ach_file: ACHFile):
    """Function to convert an ACHFile object to a JSON representation of the file content, essentially the reverse of jsonToAchFile."""
    json_data = {
        "header": {
            "record_type_code": ach_file.header['record_type_code'],
            "priority_code": ach_file.header['priority_code'],
            "immediate_destination": ach_file.header['immediate_destination'],
            "immediate_origin": ach_file.header['immediate_origin'],
            "file_creation_date": ach_file.header['file_creation_date'],
            "file_creation_time": ach_file.header['file_creation_time'],
            "file_id_modifier": ach_file.header['file_id_modifier'],
            "record_size": ach_file.header['record_size'],
            "blocking_factor": ach_file.header['blocking_factor'],
            "format_code": ach_file.header['format_code'],
            "immediate_destination_name": ach_file.header['immediate_destination_name'],
            "immediate_origin_name": ach_file.header['immediate_origin_name'],
            "reference_code": ach_file.header['reference_code']
        },
        "batches": [],
        "control": {
            "record_type_code": ach_file.control['record_type_code'],
            "batch_count": ach_file.control['batch_count'],
            "block_count": ach_file.control['block_count'],
            "entry_count": ach_file.control['entry_count'],
            "entry_hash": ach_file.control['entry_hash'],
            "total_debit_amount_cents": ach_file.control['total_debit_amount_cents'],
            "total_credit_amount_cents": ach_file.control['total_credit_amount_cents'],
            "reserved": ach_file.control['reserved']
        }
    }

    for batch in ach_file.batches:
        batch_data = {
            "header": {
                "record_type_code": batch.header['record_type_code'],
                "service_class_code": batch.header['service_class_code'],
                "company_name": batch.header['company_name'],
                "company_discretionary_data": batch.header['company_discretionary_data'],
                "company_identification": batch.header['company_identification'],
                "standard_entry_class_code": batch.header['standard_entry_class_code'],
                "company_entry_description": batch.header['company_entry_description'],
                "company_descriptive_date": batch.header['company_descriptive_date'],
                "effective_entry_date": batch.header['effective_entry_date'],
                "settlement_date": batch.header['settlement_date'],
                "originator_status_code": batch.header['originator_status_code'],
                "originating_dfi_identification": batch.header['originating_dfi_identification'],
                "batch_number": batch.header['batch_number']
            },
            "entries": [],
            "control": {
                "record_type_code": batch.control['record_type_code'],
                "service_class_code": batch.control['service_class_code'],
                "entry_count": batch.control['entry_count'],
                "entry_hash": batch.control['entry_hash'],
                "total_debit_amount_cents": batch.control['total_debit_amount_cents'],
                "total_credit_amount_cents": batch.control['total_credit_amount_cents'],
                "company_identification": batch.control['company_identification'],
                "message_authentication_code": batch.control['message_authentication_code'],
                "reserved": batch.control['reserved'],
                "originating_dfi_identification": batch.control['originating_dfi_identification'],
                "batch_number": batch.control['batch_number']
            }
        }

        for entry in batch.entries:
            entry_data = {
                "record_type_code": entry.record_type_code,
                "transaction_code": entry.transaction_code,
                "receiving_dfi_identification": entry.receiving_dfi_identification,
                "check_digit": entry.check_digit,
                "receiving_dfi_rtn": f"{entry.receiving_dfi_identification}{entry.check_digit}",
                "dfi_account_number": entry.dfi_account_number,
                "amount_cents": entry.amount_cents,
                "individual_id_number": entry.individual_id_number,
                "individual_name": entry.individual_name,
                "discretionary_data": entry.discretionary_data,
                "trace_number": entry.trace_number,
                "addenda": []
            }

            for addenda in entry.addenda:
                addenda_data = {
                    "record_type_code": addenda.record_type_code,
                    "addenda_type_code": addenda.addenda_type_code,
                    "payment_related_information": addenda.payment_related_information,
                    "addenda_sequence_number": addenda.addenda_sequence_number,
                    "entry_detail_sequence_number": addenda.entry_detail_sequence_number
                }
                entry_data["addenda"].append(addenda_data)

            batch_data["entries"].append(entry_data)
        json_data["batches"].append(batch_data)

    return json_data
    
if __name__ == "__main__":
    ach_file = ACHFile()
    print(ach_file.parse(check_formatting=False, file_path='sample2.ach'))
    
    print("Header:", ach_file.get_header())
    for i, batch in enumerate(ach_file.get_batches()):
        print(f"Batch {i+1} Header:", batch.header)
        for j, entry in enumerate(batch.entries):
            print(f"  Entry {j+1}:")
            print(f"    Record Type Code: {entry.record_type_code}")
            print(f"    Transaction Code: {entry.transaction_code}")
            print(f"    Receiving DFI Identification: {entry.receiving_dfi_identification}")
            print(f"    Check Digit: {entry.check_digit}")
            print(f"    DFI Account Number: {entry.dfi_account_number}")
            print(f"    Amount (Converted from cents): ${entry.amount_cents / 100:.2f}")
            print(f"    Individual ID Number: {entry.individual_id_number}")
            print(f"    Individual Name: {entry.individual_name}")
            print(f"    Discretionary Data: {entry.discretionary_data}")
            print(f"    Addenda Record Indicator: {entry.addenda_record_indicator}")
            print(f"    Trace Number: {entry.trace_number}")
            for k, addenda in enumerate(entry.addenda):
                print(f"      Addenda {k+1}:")
                print(f"        Record Type Code: {addenda.record_type_code}")
                print(f"        Addenda Type Code: {addenda.addenda_type_code}")
                print(f"        Payment Related Information: {addenda.payment_related_information}")
                print(f"        Addenda Sequence Number: {addenda.addenda_sequence_number}")
                print(f"        Entry Detail Sequence Number: {addenda.entry_detail_sequence_number}")
        print(f"Batch {i+1} Control:", batch.control)
    print("Control:", ach_file.get_control())

    print(ach_file.validate(is_parsed=True))

    print("\n\nACH File build result (parsed from file):")
    print(ach_file.build_ach())

    # new file creation example
    new_ach_file = ACHFile()
    new_ach_file.header = {
        'record_type_code': '1',
        'priority_code': '01',
        'immediate_destination': '090000515',
        'immediate_origin': '040104018',
        'file_creation_date': datetime.now().strftime('%y%m%d'),
        'file_creation_time': datetime.now().strftime('%H%M'),
        'file_id_modifier': 'A',
        'record_size': '094',
        'blocking_factor': '10',
        'format_code': '1',
        'immediate_destination_name': 'FRB Tungsten',
        'immediate_origin_name': 'Baguette store',
        'reference_code': ''
    }

    batch = ACHBatch()
    batch.header = {
        'record_type_code': '5',
        'service_class_code': '200',
        'company_name': 'Baguette store',
        'company_discretionary_data': '',
        'company_identification': '1313131310',
        'standard_entry_class_code': 'PPD',
        'company_entry_description': 'LEEK PAY',
        'company_descriptive_date': datetime.now().strftime('%y%m%d'),
        'effective_entry_date': (datetime.now()).strftime('%y%m%d'),
        'settlement_date': '',
        'originator_status_code': '1',
        'originating_dfi_identification': new_ach_file.header['immediate_origin'][:8],
        'batch_number': '0000001'
    }
    
    entry1 = ACHEntry().add_record(
        record_type_code='6',
        transaction_code='22',
        receiving_dfi_identification='01010101',
        check_digit='2',
        dfi_account_number='123456789',
        amount_cents=100,
        individual_id_number='',
        individual_name='Leek store',
        discretionary_data='',
        addenda_record_indicator='0',
        trace_number='040104010000001'
    )
    entry2 = ACHEntry().add_record(
        record_type_code='6',
        transaction_code='27',
        receiving_dfi_identification='01010101',
        check_digit='2',
        dfi_account_number='123456789',
        amount_cents=99900,
        individual_id_number='',
        individual_name='Leek store',
        discretionary_data='',
        addenda_record_indicator='0',
        trace_number='040104010000002'
    )
    
    batch.add_entry(entry1)
    batch.add_entry(entry2)

    batch.control = {
        'record_type_code': '8',
        'service_class_code': batch.header['service_class_code'],
        'entry_count': '',
        'entry_hash': '',
        'total_debit_amount_cents': '',
        'total_credit_amount_cents': '',
        'company_identification': batch.header['company_identification'],
        'message_authentication_code': '',
        'reserved': '',
        'originating_dfi_identification': batch.header['originating_dfi_identification'],
        'batch_number': batch.header['batch_number']
    }

    new_ach_file.control = {
        'record_type_code': '9',
        'batch_count': '',
        'block_count': '',
        'entry_count': '',
        'entry_hash': '',
        'total_debit_amount_cents': '',
        'total_credit_amount_cents': '',
        'reserved': ''
    }

    new_ach_file.add_batch(batch)

    print("\n\nACH File build result (built):")
    print(new_ach_file.build_ach())

    for line in ach_file.build_ach():
        print(line)

    print(ach_file.batches[0].control['entry_count'])

    for line in new_ach_file.build_ach():
        print(line)

    print(new_ach_file.validate(is_parsed=False))

    json_data = {
        "header": {
            "immediate_destination": "090000515",
            "immediate_origin": "040104018",
            "file_creation_date": None, # Can be none, in which case it will be set to the current date in YYMMDD format
            "file_creation_time": None, # Can be none, in which case it will be set to the current time
            "file_id_modifier": None, # Can be none, in which case it will be set to 'A'
            "immediate_destination_name": "FRB Tungsten",
            "immediate_origin_name": "Baguette store"
        },
        "batches": [
            {
                "header": {
                    "service_class_code": None, # Can be none to figure out automagically based on the transaction codes of the entries (if all debit then 225, if all credit then 220, otherwise 200 for mixed)
                    "company_name": "Baguette store",
                    "company_discretionary_data": None,
                    "company_identification": "1313131310",
                    "standard_entry_class_code": "PPD", # Currently only PPD and CCD are supported
                    "company_entry_description": "LEEK PAY", # Will be truncated to 10 characters if longer
                    "company_descriptive_date": None, # Can be none, in which case it will be set to the header date in YYMMDD format
                    "effective_entry_date": None, # Can be none, in which case it will be set to the header date in YYMMDD format
                    "settlement_date": None, # Will be set by the ACH operator, should be left empty
                    "originator_status_code": "1",
                    "originating_dfi_identification": "04010401"
                },
                "entries": [
                    {
                        "transaction_code": "22",
                        "receiving_dfi_rtn": "010101012",
                        "dfi_account_number": "39",
                        "amount_cents": 100,
                        "individual_id_number": None,
                        "individual_name": "Leek store",
                        "trace_number": "040104010000001",
                        "addenda": [
                            {
                                "payment_related_information": "31 tons of leek purchase!", # Will be truncated to 80 characters if longer
                            }
                        ]
                    },
                    {
                        "transaction_code": "22",
                        "receiving_dfi_rtn": "010101012",
                        "dfi_account_number": "39",
                        "amount_cents": 100,
                        "individual_id_number": None,
                        "individual_name": "Leek store",
                        "trace_number": "040104010000002",
                        # No addenda for this entry
                    }
                ],
            },
            {
                "header": {
                    "service_class_code": None, # Can be none to figure out automagically based on the transaction codes of the entries (if all debit then 225, if all credit then 220, otherwise 200 for mixed)
                    "company_name": "Baguette Outlet",
                    "company_discretionary_data": None,
                    "company_identification": "1555666777",
                    "standard_entry_class_code": "PPD", # Currently only PPD and CCD are supported
                    "company_entry_description": "LEEK BUY", # Will be truncated to 10 characters if longer
                    "company_descriptive_date": None, # Can be none, in which case it will be set to the header date in YYMMDD format
                    "effective_entry_date": None, # Can be none, in which case it will be set to the header date in YYMMDD format
                    "settlement_date": None, # Will be set by the ACH operator, should be left empty
                    "originator_status_code": "1",
                    "originating_dfi_identification": "12341234"
                },
                "entries": [
                    {
                        "transaction_code": "22",
                        "receiving_dfi_rtn": "514310008",
                        "dfi_account_number": "31",
                        "amount_cents": 100,
                        "individual_id_number": None,
                        "individual_name": "Leek store",
                        "trace_number": None,
                        "addenda": [
                            {
                                "payment_related_information": "31 tons of leek purchase!", # Will be truncated to 80 characters if longer
                            }
                        ]
                    },
                    {
                        "transaction_code": "22",
                        "receiving_dfi_rtn": "514310008",
                        "dfi_account_number": "31",
                        "amount_cents": 100,
                        "individual_id_number": None,
                        "individual_name": "Leek store",
                        "trace_number": None,
                        # No addenda for this entry
                    }
                ],
            }
        ],
    }

    ach_file_from_json = jsonToAchFile(json_data)
    print("\n\nACH File Header from JSON:", ach_file_from_json.get_header())
    for i, batch in enumerate(ach_file_from_json.get_batches()):
        print(f"Batch {i+1} Header from JSON:", batch.header)
        for j, entry in enumerate(batch.entries):
            print(f"  Entry {j+1} from JSON:")
            print(f"    Record Type Code: {entry.record_type_code}")
            print(f"    Transaction Code: {entry.transaction_code}")
            print(f"    Receiving DFI Identification: {entry.receiving_dfi_identification}")
            print(f"    Check Digit: {entry.check_digit}")
            print(f"    DFI Account Number: {entry.dfi_account_number}")
            print(f"    Amount (Converted from cents): ${entry.amount_cents / 100:.2f}")
            print(f"    Individual ID Number: {entry.individual_id_number}")
            print(f"    Individual Name: {entry.individual_name}")
            print(f"    Discretionary Data: {entry.discretionary_data}")
            print(f"    Addenda Record Indicator: {entry.addenda_record_indicator}")
            print(f"    Trace Number: {entry.trace_number}")
            for k, addenda in enumerate(entry.addenda):
                print(f"      Addenda {k+1} from JSON:")
                print(f"        Record Type Code: {addenda.record_type_code}")
                print(f"        Addenda Type Code: {addenda.addenda_type_code}")
                print(f"        Payment Related Information: {addenda.payment_related_information}")
                print(f"        Addenda Sequence Number: {addenda.addenda_sequence_number}")
                print(f"        Entry Detail Sequence Number: {addenda.entry_detail_sequence_number}")

    ach_file_from_json.build_ach()
    print("\n\nACH File build result from JSON:")
    for line in ach_file_from_json.build_ach():
        print(line)

    sample3_ach_file = ACHFile()
    sample3_ach_file.parse(file_path='sample3.ach')
    json_representation = achFileToJson(sample3_ach_file)
    print("\n\nJSON representation of ACH file parsed from sample3.ach:")
    print(json.dumps(json_representation, indent=4))
            