# Example of an ach file:
# 101 090000515 0401040182604050900A094101FRB Tungsten           Baguette Bank                  
# 5220Baguette store                      1313131310PPDLEEK PAY        260406   1040104010000001
# 62201010101239               0000015075               Leek store              1040104010000001
# 705A 31 tons of leek purchase!                                                     00010000001
# 62231031031239               0000015075               Leek store              0040104010000002
# 822000000300320411320000000000000000000301501313131310                         040104010000001
# 9000001000001000000030032041132000000000000000000030150                                       
# 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
# 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
# 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

import os

class ACHEntry:
    def __init__(self):
        self.record_type_code = None
        self.transaction_code = None
        self.receiving_dfi_identification = None
        self.check_digit = None
        self.dfi_account_number = None
        self.amount_cents = None
        self.individual_id_number = None
        self.individual_name = None
        self.discretionary_data = None 
        self.addenda_record_indicator = None 
        self.trace_number = None
        self.addenda = []

    def add_addenda(self, addenda):
        self.addenda.append(addenda)

    def parse_record(self, line):
        self.record_type_code = line[0]
        self.transaction_code = line[1:3]
        self.receiving_dfi_identification = line[3:11].strip()
        self.check_digit = line[11]
        self.dfi_account_number = line[12:29].strip()
        self.amount_cents = int(line[29:39]) # Amount in cents, convert to dollars by dividing by 100
        self.individual_id_number = line[39:54].strip()
        self.individual_name = line[54:76].strip()
        self.discretionary_data = line[76:78].strip() # Note: This field is optional and can be used by the originator or ODFI for any purpose they choose. It may contain information that is relevant to the processing of the entry, but it is not standardized and may not be used by all originators or ODFIs.
        self.addenda_record_indicator = line[78] # Note: This field indicates whether there are addenda records associated with this entry. If it is '1', there is at least one addenda record; if it is '0', there are no addenda records.
        self.trace_number = line[79:94].strip() # Note: This field is critical for tracking the transaction through the ACH network and should be unique for each entry. It is often generated by the ODFI and may include a combination of the ODFI's routing number and a sequential number to ensure uniqueness.
        self.addenda = [] # This will hold any addenda records associated with this entry
        return self

    def add_record(self, record : dict):
        """
        Adds a record to the entry.
        record = {
            'record_type_code': None,
            'transaction_code': None,
            'receiving_dfi_identification': None,
            'check_digit': None,
            'dfi_account_number': None,
            'amount_cents': None,
            'individual_id_number': None,
            'individual_name': None,
            'discretionary_data': None, 
            'addenda_record_indicator': None, 
            'trace_number': None
        }
        """
        self.record_type_code = record['record_type_code']
        self.transaction_code = record['transaction_code']
        self.receiving_dfi_identification = record['receiving_dfi_identification']
        self.check_digit = record['check_digit']
        self.dfi_account_number = record['dfi_account_number']
        self.amount_cents = record['amount_cents']
        self.individual_id_number = record['individual_id_number']
        self.individual_name = record['individual_name']
        self.discretionary_data = record['discretionary_data']
        self.addenda_record_indicator = record['addenda_record_indicator']
        self.trace_number = record['trace_number']
    
    def add_record(self, record_type_code, transaction_code, receiving_dfi_identification, check_digit, dfi_account_number, amount_cents, individual_id_number, individual_name, discretionary_data, addenda_record_indicator, trace_number):
        self.record_type_code = record_type_code
        self.transaction_code = transaction_code
        self.receiving_dfi_identification = receiving_dfi_identification
        self.check_digit = check_digit
        self.dfi_account_number = dfi_account_number
        self.amount_cents = amount_cents
        self.individual_id_number = individual_id_number
        self.individual_name = individual_name
        self.discretionary_data = discretionary_data
        self.addenda_record_indicator = addenda_record_indicator
        self.trace_number = trace_number

class ACHAddenda:
    def __init__(self):
        self.record_type_code = None
        self.addenda_type_code = None
        self.payment_related_information = None
        self.addenda_sequence_number = None
        self.entry_detail_sequence_number = None

    def parse_record(self, line):
        self.record_type_code = line[0]
        self.addenda_type_code = line[1:3]
        self.payment_related_information = line[3:83].strip() # Note: This is a free-form alphanumeric field that can contain any information related to the payment. It is often used to provide additional details about the transaction, such as invoice numbers, customer references, or other relevant information that can help the receiver understand the purpose of the payment.
        self.addenda_sequence_number = line[83:87].strip() # Note: This field indicates the sequence of addenda records associated with an entry. Hovewer the PPD CCD and WEB only allow one addenda record, so this field should be '0001' for those SEC codes. For other SEC codes that allow multiple addenda records, this field should be incremented for each additional addenda record associated with the same entry.
        self.entry_detail_sequence_number = line[87:94].strip() # Note: This field should match the last 7 digits of the trace number in the corresponding entry detail record to ensure proper association between the addenda and its entry.
        return self

    def add_record(self, record : dict):
        """
        Adds a record to the addenda.
        record = {
            'record_type_code': None,
            'addenda_type_code': None,
            'payment_related_information': None,
            'addenda_sequence_number': None,
            'entry_detail_sequence_number': None
        }
        """
        self.record_type_code = record['record_type_code']
        self.addenda_type_code = record['addenda_type_code']
        self.payment_related_information = record['payment_related_information']
        self.addenda_sequence_number = record['addenda_sequence_number']
        self.entry_detail_sequence_number = record['entry_detail_sequence_number']

    def add_record(self, record_type_code, addenda_type_code, payment_related_information, addenda_sequence_number, entry_detail_sequence_number):
        self.record_type_code = record_type_code
        self.addenda_type_code = addenda_type_code
        self.payment_related_information = payment_related_information
        self.addenda_sequence_number = addenda_sequence_number
        self.entry_detail_sequence_number = entry_detail_sequence_number

class ACHBatch:
    def __init__(self):
        self.header = {
            'record_type_code': None,
            'service_class_code': None,
            'company_name': None,
            'company_discretionary_data': None,
            'company_identification': None,
            'standard_entry_class_code': None,
            'company_entry_description': None,
            'company_descriptive_date': None,
            'effective_entry_date': None,
            'settlement_date': None,
            'originator_status_code': None,
            'originating_dfi_identification': None,
            'batch_number': None
        }
        self.entries = []
        self.control = {
            'record_type_code': None,
            'service_class_code': None,
            'entry_count': None,
            'entry_hash': None,
            'total_debit_amount_cents': None,
            'total_credit_amount_cents': None,
            'company_identification': None,
            'message_authentication_code': None,
            'reserved': None
        }

    def parse_header(self, header_line):
        self.header = {
            'record_type_code': header_line[0],
            'service_class_code': header_line[1:4], # Note: This field identifies the general classification of dollar entries to be exchanged.
            'company_name': header_line[4:20].strip(), # Note: This field is critical for identifying the originator and should be consistent across all entries in the batch. It should be a name that is recognizable to the receiver, such as the name of the business or individual initiating the transaction.
            'company_discretionary_data': header_line[20:40].strip(), # Note: This field is optional and can be used by the originator or ODFI for any purpose they choose. It may contain information that is relevant to the processing of the batch, but it is not standardized and may not be used by all originators or ODFIs. If present, it should be consistent across all entries in the batch.
            'company_identification': header_line[40:50].strip(), # Note: This field is critical for identifying the originator and is often used in conjunction with the ODFI's routing number to uniquely identify the source of the transaction. It must be consistent across all entries in the batch and should be assigned by the ODFI to ensure uniqueness and proper tracking of transactions.
            'standard_entry_class_code': header_line[50:53].strip(), # Note: This is a critical field that determines the type of transaction and has specific formatting rules based on the SEC code
            'company_entry_description': header_line[53:63].strip(), # Note: Some SEC codes require specific values for this field, but in general it's a free-form alphanumeric field
            'company_descriptive_date': header_line[63:69].strip(), # Note: This is a free-form alphanumeric field, not a calendar date
            'effective_entry_date': header_line[69:75].strip(), # Note: This is the YYMMDD format, not a calendar date
            'settlement_date': header_line[75:78].strip(), # Note: This is the Julian date format (DDD), not a calendar date
            'originator_status_code': header_line[78:79].strip(), # Note: This field indicates the status of the originator
            'originating_dfi_identification': header_line[79:87].strip(),
            'batch_number': header_line[87:94].strip()
        }
        return self

    def add_header(self, header : dict):
        """
        Adds a header to the batch.
        header = {
            'record_type_code': None,
            'service_class_code': None,
            'company_name': None,
            'company_discretionary_data': None,
            'company_identification': None,
            'standard_entry_class_code': None,
            'company_entry_description': None,
            'company_descriptive_date': None,
            'effective_entry_date': None,
            'settlement_date': None,
            'originator_status_code': None,
            'originating_dfi_identification': None,
            'batch_number': None
        }
        """
        self.header = header

    def add_header(self, record_type_code, service_class_code, company_name, company_discretionary_data, company_identification, standard_entry_class_code, company_entry_description, company_descriptive_date, effective_entry_date, settlement_date, originator_status_code, originating_dfi_identification, batch_number):
        self.header = {
            'record_type_code': record_type_code,
            'service_class_code': service_class_code,
            'company_name': company_name,
            'company_discretionary_data': company_discretionary_data,
            'company_identification': company_identification,
            'standard_entry_class_code': standard_entry_class_code,
            'company_entry_description': company_entry_description,
            'company_descriptive_date': company_descriptive_date,
            'effective_entry_date': effective_entry_date,
            'settlement_date': settlement_date,
            'originator_status_code': originator_status_code,
            'originating_dfi_identification': originating_dfi_identification,
            'batch_number': batch_number
        }
    
    def add_entry(self, entry):
        self.entries.append(entry)

    def add_control(self, control):
        """
        Adds a control to the batch.
        control = {
            'record_type_code': None,
            'service_class_code': None,
            'entry_count': None,
            'entry_hash': None,
            'total_debit_amount_cents': None,
            'total_credit_amount_cents': None,
            'company_identification': None,
            'message_authentication_code': None,
            'reserved': None
        }
        """
        self.control = control

    def add_control(self, record_type_code, service_class_code, entry_count, entry_hash, total_debit_amount_cents, total_credit_amount_cents, company_identification, message_authentication_code, reserved):
        self.control = {
            'record_type_code': record_type_code,
            'service_class_code': service_class_code,
            'entry_count': entry_count,
            'entry_hash': entry_hash,
            'total_debit_amount_cents': total_debit_amount_cents,
            'total_credit_amount_cents': total_credit_amount_cents,
            'company_identification': company_identification,
            'message_authentication_code': message_authentication_code,
            'reserved': reserved
        }

    def parse_control(self, control_line):
        self.control = {
            'record_type_code': control_line[0],
            'service_class_code': control_line[1:4].strip(),
            'entry_count': control_line[4:10].strip(),
            'entry_hash': control_line[10:20].strip(),
            'total_debit_amount_cents': int(control_line[20:32]), # Amount in cents, convert to dollars by dividing by 100
            'total_credit_amount_cents': int(control_line[32:44]), # Amount in cents, convert to dollars by dividing by 100
            'company_identification': control_line[44:54].strip(),
            'message_authentication_code': control_line[54:73].strip(), # Note: This field is optional and can be used by the ODFI for any purpose they choose. It may contain information that is relevant to the processing of the batch, but it is not standardized and may not be used by all ODFIs.
            'reserved': control_line[73:94].strip()
        }


class ACHFile:
    def __init__(self):
        self.header = {
            'record_type_code': None, # Always "1"
            'priority_code': None, # Always "01"
            'immediate_destination': None,
            'immediate_origin': None,
            'file_creation_date': None,
            'file_creation_time': None,
            'file_id_modifier': None,
            'record_size': None, # Always "094"
            'blocking_factor': None, # Always "10"
            'format_code': None, # Always "1"
            'immediate_destination_name': None,
            'immediate_origin_name': None,
            'reference_code': None
        }
        self.batches = []
        self.control = None
        self.file_name = None # Name of file if parsed from other source
        self.block_count = None # Number of 10-line blocks in the file, calculated during parsing
        self.lines = None # Lines of the file, stored during parsing for validation purposes
    
    @staticmethod
    def validate_rtn_check_digit(rtn):
        """
        Validate RTN (Routing Transit Number) check digit.
        Formula: (3(d1 + d4 + d7) + 7(d2 + d5 + d8) + (d3 + d6 + d9)) mod 10 = 0
        
        Args:
            rtn: 9-digit routing number as string
            
        Returns:
            True if valid, False otherwise
        """
        if not rtn or len(rtn) != 9 or not rtn.isdigit():
            return False
        
        digits = [int(d) for d in rtn]
        # d1=0, d2=1, d3=2, d4=3, d5=4, d6=5, d7=6, d8=7, d9=8
        checksum = (3 * (digits[0] + digits[3] + digits[6]) + 
                    7 * (digits[1] + digits[4] + digits[7]) + 
                    (digits[2] + digits[5] + digits[8]))
        
        return checksum % 10 == 0

    def parse(self, file_path, check_formatting=False):
        """Parses an ACH file from the given file path."""

        def build_header_line():
            file_id_modifier = self.header.get('file_id_modifier') or ''
            return f"FH,1,LIVE"

        def build_format_error_ack(message):
            return "\n".join([
                build_header_line(),
                f"E,F,0,9999,{message}",
            ])

        if not os.path.isabs(file_path):
            script_dir = os.path.dirname(os.path.abspath(__file__))
            file_path = os.path.join(script_dir, file_path)
        
        with open(file_path, 'r') as f:
            lines = f.readlines()
        self.file_name = os.path.basename(file_path)
        self.lines = lines

        self.block_count = len(lines) // 10
        try:
            if not lines:
                raise ValueError("ACH file is empty")
            
            # Checks if the file contains a whole number of 10-blocks (i.e. 10, 20, 30, etc. lines) and raises an error if not
            self.is_file_of_10_blocks(lines)
            
            # Parse header
            try: 
                header_line = lines[0].rstrip('\n\r')
                self.check_line_is_94_chars(header_line)
                self.parse_header(header_line)
            except Exception as e:
                raise ValueError(f"Error parsing header: {e}")
            
            # Parse batches
            current_batch = None
            saw_file_control = False
            for line in lines[1:]:
                line = line.rstrip('\n\r')
                self.check_line_is_94_chars(line)
                record_type_code = line[0]

                if saw_file_control:
                    if line != '9' * 94:
                        raise ValueError("Found non-padding content after file control record")
                    continue

                if record_type_code == '5': # Batch header
                    if current_batch is not None:
                        raise ValueError("Found batch header while already processing a batch")
                    current_batch = ACHBatch().parse_header(line)
                elif record_type_code == '6': # Entry detail
                    if current_batch is None:
                        raise ValueError("Found entry detail without a batch header")
                    current_batch.add_entry(ACHEntry().parse_record(line))
                elif record_type_code == '7': # Addenda record
                    if current_batch is None:
                        raise ValueError("Found addenda record without a batch header")
                    if not current_batch.entries:
                        raise ValueError("Found addenda record without an entry detail")
                    current_batch.entries[-1].addenda.append(ACHAddenda().parse_record(line))
                elif record_type_code == '8': # Batch control
                    if current_batch is None:
                        raise ValueError("Found batch control without a batch header")
                    current_batch.parse_control(line)
                    self.add_batch(current_batch)
                    current_batch = None
                elif record_type_code == '9': # File control
                    if current_batch is not None:
                        raise ValueError("Found file control while still processing a batch")
                    if self.control is None:
                        self.parse_control(line)
                        saw_file_control = True
                    elif line != '9' * 94:
                        raise ValueError("Expected all-9 padding after file control record")
                else:
                    raise ValueError(f"Unknown record type code: {record_type_code}")
        except Exception as e:
            if check_formatting:
                return build_format_error_ack(str(e))
            else:
                raise

    def check_line_is_94_chars(self, line):
        if len(line) != 94:
            raise ValueError(f"Line is not 94 characters long: {line}")
        
    def is_file_of_10_blocks(self, lines):
        if len(lines) % 10 != 0:
            raise ValueError(f"File does not contain a whole number of 10-blocks: {len(lines)} lines")
        
    def parse_header(self, line):
        self.header = {
            'record_type_code': line[0],
            'priority_code': line[1:3],
            'immediate_destination': line[3:13].strip(),
            'immediate_origin': line[13:23].strip(),
            'file_creation_date': line[23:29], # YYMMDD format
            'file_creation_time': line[29:33], # HHMM format
            'file_id_modifier': line[33], # A-Z, 0-9
            'record_size': line[34:37], # Always "094"
            'blocking_factor': line[37:39], # Always "10"
            'format_code': line[39], # Always "1"
            'immediate_destination_name': line[40:63].strip(),
            'immediate_origin_name': line[63:86].strip(),
            'reference_code': line[86:94].strip()
        }

    def parse_control(self, line):
        self.control = {
            'record_type_code': line[0],
            'batch_count': line[1:7].strip(),
            'block_count': line[7:13].strip(),
            'entry_count': line[13:21].strip(),
            'entry_hash': line[21:31].strip(),
            'total_debit_amount_cents': int(line[31:43]), # Amount in cents, convert to dollars by dividing by 100
            'total_credit_amount_cents': int(line[43:55]), # Amount in cents, convert to dollars by dividing by 100
            'reserved': line[55:94].strip()
        }
    
    def add_batch(self, batch):
        self.batches.append(batch)

    def get_header(self):
        return self.header

    def get_batches(self):
        return self.batches

    def get_control(self):
        return self.control
    
    def get_block_number(self):
        return self.block_count
    
    def validate(self, is_parsed=False, immediate_destination=None, immediate_origin=None):
        line_errors= []
        
        def build_header_line():
            file_id_modifier = self.header.get('file_id_modifier') or ''
            return f"FH,1,LIVE,{file_id_modifier}"

        def build_success_ack():
            if is_parsed:
                if not self.file_name:
                    raise ValueError("It looks like you're trying to pass unparsed data to the validate function. To use this function, create the .ach file first and than parse it using the parse function.")
                return "\n".join([
                        build_header_line(),
                        f"R,{self.get_block_number()},{self.get_block_number()*10}",
                    ])
            else:
                return "\n".join([
                    build_header_line(),
                    "File is valid, to generate successful ACK generate the .ach file, parse it using the parse function and then call validate with is_parsed=True",
                ])

        def build_format_error_ack(message):
            return "\n".join([
                build_header_line(),
                f"E,F,0,9999,{message}",
            ])

        def build_line_error_ack(errors):
            lines = [build_header_line()]
            for error in errors:
                if isinstance(error, dict):
                    error_type = error.get('error_type', 'R')
                    line_number = error.get('line_number', 0)
                    error_code = error.get('error_code', 5000)
                    message = error.get('message', 'Invalid Account')
                else:
                    if len(error) == 2:
                        line_number, message = error
                        error_type = 'L'
                        error_code = 5000
                    elif len(error) == 3:
                        line_number, error_code, message = error
                        error_type = 'L'
                    else:
                        error_type, line_number, error_code, message = error

                lines.append(f"E,{error_type},{line_number},{error_code},{message}")

            return "\n".join(lines)

        def check_immediate_destination():
            if immediate_destination and self.header['immediate_destination'] != immediate_destination:
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1001,
                    'message': f"Immediate destination does not match expected value: {self.header['immediate_destination']} != {immediate_destination}"
                })

            if not self.validate_rtn_check_digit(self.header['immediate_destination']):
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1007,
                    'message': f"Invalid RTN check digit in immediate destination: {self.header['immediate_destination']}"
                })
            
        def check_immediate_origin():
            if immediate_origin and self.header['immediate_origin'] != immediate_origin:
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1002,
                    'message': f"Immediate origin does not match expected value: {self.header['immediate_origin']} != {immediate_origin}"
                })

            if not self.validate_rtn_check_digit(self.header['immediate_origin']):
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1008,
                    'message': f"Invalid RTN check digit in immediate origin: {self.header['immediate_origin']}"
                })

        def check_entry_rtns():
            """Validate RTN check digits for all entry details"""
            line_number = 2  # Start after header
            for batch_idx, batch in enumerate(self.batches):
                for entry_idx, entry in enumerate(batch.entries):
                    rtn = str(entry.receiving_dfi_identification) + str(entry.check_digit)
                    if rtn and not self.validate_rtn_check_digit(rtn):
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5001,
                            'message': f"Invalid RTN check digit: {rtn}"
                        })
                    if entry.addenda_record_indicator == '1' and not entry.addenda:
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5002,
                            'message': f"Addenda record indicator is '1' but no addenda records found for entry with trace number {entry.trace_number}"
                        })
                    
                    if entry.addenda_record_indicator == '0' and entry.addenda:
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5003,
                            'message': f"Addenda record indicator is '0' but addenda records found for entry with trace number {entry.trace_number}"
                        })

                    if entry.addenda_record_indicator == '0':
                        line_number += 1
                    else:
                        line_number += 1 + len(entry.addenda)

        def check_header():
            header = self.header
            control = self.control

            if header['record_type_code'] != '1':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1000,
                    'message': f"Invalid record type code in header: {header['record_type_code']}"
                })
            
            if header['priority_code'] != '01':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1003,
                    'message': f"Invalid priority code in header: {header['priority_code']}"
                })
            
            if header['record_size'] != '094':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1004,
                    'message': f"Invalid record size in header: {header['record_size']}"
                })

            if header['blocking_factor'] != '10':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1005,
                    'message': f"Invalid blocking factor in header: {header['blocking_factor']}"
                })

            if header['format_code'] != '1':
                line_errors.append({
                    'error_type': 'H',
                    'line_number': 1,
                    'error_code': 1006,
                    'message': f"Invalid format code in header: {header['format_code']}"
                })

            line_count = 1 + sum(1 + len(entry.addenda) for batch in self.batches for entry in batch.entries) + len(self.batches)*2 + 1 # header + entry and addenda records + batch headers and controls + file control

            if control['record_type_code'] != '9':
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3000,
                    'message': f"Invalid record type code in file control: {control['record_type_code']}"
                })

            if control['batch_count'] != str(len(self.batches)).zfill(6):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3002,
                    'message': f"Batch count in file control does not match actual number of batches in file: {control['batch_count']} != {str(len(self.batches)).zfill(6)}"
                })
            
            if control['block_count'] != str(self.block_count).zfill(6):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3003,
                    'message': f"Block count in file control does not match actual number of blocks in file: {control['block_count']} != {str(self.block_count).zfill(6)}"
                })

            entry_and_addenda_count = sum(1 + len(entry.addenda) for batch in self.batches for entry in batch.entries)
            if control['entry_count'] != str(entry_and_addenda_count).zfill(8):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3004,
                    'message': f"Entry count in file control does not match actual number of entry and addenda records in file: {control['entry_count']} != {str(entry_and_addenda_count).zfill(8)}"
                })

            entry_hash = sum(int(entry.receiving_dfi_identification) for batch in self.batches for entry in batch.entries) % 10**10
            if control['entry_hash'] != str(entry_hash).zfill(10):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3005,
                    'message': f"Entry hash in file control does not match calculated entry hash: {control['entry_hash']} != {str(entry_hash).zfill(10)}"
                })

            if control['total_debit_amount_cents'] != sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['27', '37', '47', '57', '67', '87']):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3006,
                    'message': f"Total debit amount in file control does not match calculated total debit amount: {control['total_debit_amount_cents']} != {sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['27', '37', '47', '57', '67', '87'])}"
                })

            if control['total_credit_amount_cents'] != sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['22', '32', '42', '52', '62', '82']):
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3007,
                    'message': f"Total credit amount in file control does not match calculated total credit amount: {control['total_credit_amount_cents']} != {sum(entry.amount_cents for batch in self.batches for entry in batch.entries if entry.transaction_code in ['22', '32', '42', '52', '62', '82'])}"
                })

            if control['reserved'] != '':
                line_errors.append({
                    'error_type': 'C',
                    'line_number': line_count,
                    'error_code': 3008,
                    'message': f"Reserved field in file control is not empty: {control['reserved']}"
                })

            if is_parsed and self.batches:
                check_entry_rtns()
        
        def check_batch(start_line_number):
            line_number = start_line_number
            for batch_idx, batch in enumerate(self.batches):
                if batch.header['record_type_code'] != '5':
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2000,
                        'message': f"Invalid record type code in batch header: {batch.header['record_type_code']}"
                    })
                if batch.header['service_class_code'] not in ['200', '220', '225']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2001,
                        'message': f"Invalid service class code in batch header: {batch.header['service_class_code']} 200 - Mixed Debits and Credits, 220 - Credits Only, 225 - Debits Only"
                    })

                if batch.header['standard_entry_class_code'] not in ['PPD', 'CCD', 'WEB', 'TEL']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2002,
                        'message': f"Invalid standard entry class code in batch header: {batch.header['standard_entry_class_code']} Only 4 standard entry class codes are supported: PPD - Prearranged Payment and Deposit Entry, CCD - Corporate Credit or Debit, WEB - Internet-Initiated Entry, TEL - Telephone-Initiated Entry"
                    })

                if batch.header['originator_status_code'] not in ['1', '2', '3']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2003,
                        'message': f"Invalid originator status code in batch header: {batch.header['originator_status_code']} 1 - Originator is a financial institution, 2 - Originator is a non-financial institution, 3 - Originator is a government entity"
                    })

                if batch.header['originating_dfi_identification'] != self.header['immediate_origin'][:8]:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2004,
                        'message': f"Originating DFI identification in batch header does not match immediate origin in file header: {batch.header['originating_dfi_identification']} != {self.header['immediate_origin'][:8]}"
                    })

                previous_entry_trace_number = int(batch.header['originating_dfi_identification'] + '0000000')
                for entry in batch.entries:
                    if batch.header['service_class_code'] == '225':
                        if entry.transaction_code not in ['27', '28', '37', '38', '47', '48', '57', '58', '67', '68', '87', '88']:
                            line_errors.append({
                                'error_type': 'E',
                                'line_number': line_number,
                                'error_code': 3001,
                                'message': f"Invalid transaction code for debit entry in batch with service class code 225: {entry.transaction_code}"
                            })

                    if batch.header['service_class_code'] == '220':
                        if entry.transaction_code not in ['22', '23', '32', '33', '42', '43', '52', '53', '62', '63', '82', '83']:
                            line_errors.append({
                                'error_type': 'E',
                                'line_number': line_number,
                                'error_code': 3000,
                                'message': f"Invalid transaction code for credit entry in batch with service class code 220: {entry.transaction_code}"
                            })

                    if int(entry.trace_number) <= previous_entry_trace_number:
                        line_errors.append({
                            'error_type': 'L',
                            'line_number': line_number,
                            'error_code': 5004,
                            'message': f"Entry trace number out of order: {entry.trace_number} should be greater than {previous_entry_trace_number} (trace numbers can skip but not go backwards)"
                        })
                    previous_entry_trace_number = int(entry.trace_number)
                    
                    line_number += 1 + len(entry.addenda)  # Account for entry detail and addenda lines

                line_number += 1  # Place self at batch control line

                entry_and_addenda_count = sum(1 + len(entry.addenda) for entry in batch.entries)
                if batch.control['entry_count'] != str(entry_and_addenda_count).zfill(6):
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2005,
                        'message': f"Entry count in batch control does not match actual number of entry and addenda records in batch: {batch.control['entry_count']} != {str(entry_and_addenda_count).zfill(6)}"
                    })
                
                entry_hash = sum(int(entry.receiving_dfi_identification) for entry in batch.entries) % 10**10
                if batch.control['entry_hash'] != str(entry_hash).zfill(10):
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2006,
                        'message': f"Entry hash in batch control does not match calculated entry hash: {batch.control['entry_hash']} != {str(entry_hash).zfill(10)}"
                    })

                total_debit_amount_cents = sum(entry.amount_cents for entry in batch.entries if entry.transaction_code in ['27', '37', '47', '57', '67', '87'])
                if batch.control['total_debit_amount_cents'] != total_debit_amount_cents:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2007,
                        'message': f"Total debit amount in batch control does not match calculated total debit amount: {batch.control['total_debit_amount_cents']} != {total_debit_amount_cents}"
                    })

                total_credit_amount_cents = sum(entry.amount_cents for entry in batch.entries if entry.transaction_code in ['22', '32', '42', '52', '62', '82'])
                if batch.control['total_credit_amount_cents'] != total_credit_amount_cents:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2008,
                        'message': f"Total credit amount in batch control does not match calculated total credit amount: {batch.control['total_credit_amount_cents']} != {total_credit_amount_cents}"
                    })

                if batch.control['company_identification'] != batch.header['company_identification']:
                    line_errors.append({
                        'error_type': 'B',
                        'line_number': line_number,
                        'error_code': 2009,
                        'message': f"Company identification in batch control does not match company identification in batch header: {batch.control['company_identification']} != {batch.header['company_identification']}"
                    })

                return line_number + 1  # Return line number of next batch header or file control after this batch

        try:
            check_immediate_destination()
            check_immediate_origin()
            check_header()
            last_number = 2
            for batch in self.batches:
                last_number = check_batch(last_number)
        except ValueError as error:
            return build_format_error_ack(str(error))

        if line_errors:
            return build_line_error_ack(line_errors)

        return build_success_ack()
    
if __name__ == "__main__":
    ach_file = ACHFile()
    print(ach_file.parse(check_formatting=False, file_path='sample2.ach'))
    
    print("Header:", ach_file.get_header())
    for i, batch in enumerate(ach_file.get_batches()):
        print(f"Batch {i+1} Header:", batch.header)
        for j, entry in enumerate(batch.entries):
            print(f"  Entry {j+1}:")
            print(f"    Record Type Code: {entry.record_type_code}")
            print(f"    Transaction Code: {entry.transaction_code}")
            print(f"    Receiving DFI Identification: {entry.receiving_dfi_identification}")
            print(f"    Check Digit: {entry.check_digit}")
            print(f"    DFI Account Number: {entry.dfi_account_number}")
            print(f"    Amount (Converted from cents): ${entry.amount_cents / 100:.2f}")
            print(f"    Individual ID Number: {entry.individual_id_number}")
            print(f"    Individual Name: {entry.individual_name}")
            print(f"    Discretionary Data: {entry.discretionary_data}")
            print(f"    Addenda Record Indicator: {entry.addenda_record_indicator}")
            print(f"    Trace Number: {entry.trace_number}")
            for k, addenda in enumerate(entry.addenda):
                print(f"      Addenda {k+1}:")
                print(f"        Record Type Code: {addenda.record_type_code}")
                print(f"        Addenda Type Code: {addenda.addenda_type_code}")
                print(f"        Payment Related Information: {addenda.payment_related_information}")
                print(f"        Addenda Sequence Number: {addenda.addenda_sequence_number}")
                print(f"        Entry Detail Sequence Number: {addenda.entry_detail_sequence_number}")
        print(f"Batch {i+1} Control:", batch.control)
    print("Control:", ach_file.get_control())

    print(ach_file.validate(is_parsed=True))